sudo: false
language: objective-c
osx_image: xcode8.2
cache: cocoapods
podfile: OAStatusItemKit/Podfile

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- (cd OAStatusItemKit; pod update)
- make test
- pod lib lint --quick

after_success:
- bash <(curl -s https://codecov.io/bash)
